### ISSUE TITLE
Update the docs section to use Sphinx

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#12]
In project/docs, replace the docs folder with Sphinx documentation. 

See https://github.com/VOLTTRON/volttron/tree/main/docs as an example. See https://www.sphinx-doc.org/en/master/tutorial/index.html for Sphinx documentation and tutorials.

**Comment by kefeimo** [comment]
Fixed by https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/23
Manually closed.
