### ISSUE TITLE
Add a default config file at the top level of Agent source code template

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#13]
Agents should have an example  'config' file. For examples, see https://github.com/VOLTTRON/volttron/tree/main/services/core/OpenEISHistorian. Other config examples can be seen in every agent in https://github.com/VOLTTRON/volttron/tree/main/services/core.

**Comment by kefeimo** [comment]
fixed by #43. Manually closed.
