### ISSUE TITLE
Remove cruft files 

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#14]
Current output of copier is shown below on the left side:

![image](https://user-images.githubusercontent.com/6901848/160945385-f9129fc8-0c79-40ec-8338-f97711b2898f.png)

Cruft files or directories to remove:

* docs/css
* docs/reference
* unnecessary, duplicate directory of <listener-dummy>
* scripts/

**Comment by kefeimo** [comment]
The way to get rid of /scripts is not straightforward due to the following error. 
We might find an elegant way to resolve this, but so far I suggest leave it like this.

![image](https://user-images.githubusercontent.com/28743873/161108189-8b675ffc-831d-4c7f-baab-56ac77f778e3.png)

**Comment by kefeimo** [comment]
After removing the two-layer nested project dir, the tree looks like the following
![image](https://user-images.githubusercontent.com/28743873/161472583-8a7a49df-5dde-43dc-b109-c0517c18d4b4.png)

Now the focus is `/docs/`. I am planning to use Sphinx-quickstart scoffold (with separate source and build dirs). 
![image](https://user-images.githubusercontent.com/28743873/161471621-9d8ef3fb-3209-4790-a5eb-3d46cb517af6.png)

Also take consideration of the current scaffold of [/volttron/docs](https://github.com/VOLTTRON/volttron/tree/main/docs)
