### ISSUE TITLE
Resolve Copier command using specified (non-default) branch

### ISSUE THREAD

**Issue by kefeimo** [VOLTTRON/copier-poetry-volttron-agent#15]
Derived from #8 , #11 

Issue Description

How to specify branch when using
```copier "https://github.com/VOLTTRON/copier-poetry-volttron-agent.git" /path/to/your/new/project```
Right now, I need to set a non-main branch default then run copier command

**Comment by kefeimo** [comment]
Resolution (not ideal but more elegant than the former walkaround--change branch as default)

Idea:
use copier's ```—vcs-ref``` tag. It is to checkout a ref/tag not branch. But actually a branch can is considered a reference. (See [Getting geeky with Git #3. The branch is a reference - Marcin ...](https://wanago.io/2020/05/04/geeky-with-git-branch-reference/)

Steps:
![image](https://user-images.githubusercontent.com/28743873/161102452-775bf49e-6e6d-408d-86e6-45c4fccf5990.png)
![image](https://user-images.githubusercontent.com/28743873/161102499-57bac66b-3814-474c-a1db-262445dd62ea.png)

or in CLI
![image](https://user-images.githubusercontent.com/28743873/161102569-fba9f693-c261-4c39-8210-60a48c90980e.png)
![image](https://user-images.githubusercontent.com/28743873/161102609-335749d1-2404-4611-9ef4-529ec3b1147d.png)

Close for now (will update if Copier introduce new tags like ```--branch```)

**Comment by craigpnnl** [comment]
The reason copier does this is because we can have a template that updates over time.  For example we decide to release a version 0.2.0 that has a certain structure of template...then later we release 0.3.3.  The user ran it with 0.2.0 originally and then can run copier again to upgrade the cruf stuff over the top of the old (if they want to overwrite).

So to follow the copier path we should release our copier tag/release and then modify and release to continue the upgrading of the agent.

**Comment by craigpnnl** [comment]
Hopefully that comment makes sense.  https://copier.readthedocs.io/en/latest/comparisons/  see template updates

**Comment by kefeimo** [comment]
Thanks @craig8 for the explanation. I agree for Copier template user, it is rare to run into the problem that need the template from branch other than main. The reason I created this issue is more like a note for template developers when they need to interact with non-main branches. 
If my argument holds, the question is should the README mention how to use Copier to interact with non-default branches even if it is mainly for template developers.
