### ISSUE TITLE
Move Codeql workflow to Project folder

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#24]
Codeql workflow, https://github.com/VOLTTRON/copier-poetry-volttron-agent/blob/develop/.github/workflows/code_analysis.yml, is in the wrong folder. It should be in the projects/.github folder.

**Comment by kefeimo** [comment]
Fixed by https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/25
Manually closed.
