### ISSUE TITLE
Update README for Agent template

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#29]
The README for the Agent template needs to updated with more helpful sections on getting started, development, ci/cd tooling, etc. The README should be more robust and look like: https://github.com/VOLTTRON/volttron-openadr-ven/blob/main/README.md and https://github.com/VOLTTRON/volttron-listener-agent/blob/main/README.md

**Comment by kefeimo** [comment]
fixed by #40 
manually closed.
