### ISSUE TITLE
Static code analysis through CodeQL

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#3]
Create workflow actions that uses CodeQL to determine code vulnerabilities.

**Comment by bonicim** [comment]
Use example from https://github.com/VOLTTRON/volttron-core/blob/develop/.github/workflows/code_analysis.yml

**Comment by kefeimo** [comment]
Fixed by https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/16. 
Manually closed.

**Comment by kefeimo** [comment]
Fixed by https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/16.
Manually closed.
