### ISSUE TITLE
Update agent.py in template

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#34]
The [agent.py](https://github.com/VOLTTRON/copier-poetry-volttron-agent/blob/develop/project/%5B%5B%20python_package_distribution_name%20%5D%5D/agent.py.jinja) needs to be replaced by the [agent.py example when using vpkg](https://volttron.readthedocs.io/en/develop/developing-volttron/developing-agents/agent-development.html#agent-skeleton).

**Comment by kefeimo** [comment]
fixed by [Update agent.py template](https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/45#)
#45.
Manually closed.
