### ISSUE TITLE
Update pre-commit 

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#35]
The .pre-commit-config.yaml uses 'black' . This is no longer necessary because 'yapf' already has it. Remove 'black' from the pre-commit hook. 

Also, make any other updates based on using this pre-commit hook.

**Comment by bonicim** [comment]
This issues is being addressed in #30

**Comment by kefeimo** [comment]
@bonicim, can you check the part related to "black" as well? According to 04/20 's work meeting, we want to get rid of that.

**Comment by kefeimo** [comment]
duplicated with #4 
maunally closed
