### ISSUE TITLE
Update dev dependencies in agent project

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#36]
Currently, the project's [docs](https://github.com/VOLTTRON/copier-poetry-volttron-agent/tree/develop/project/docs) requires the user to manually install sphinx dependencies in order to create documentation. 

Instead, these dependencies should already be part of the initial install (i.e. poetry install). 

In addition, update the pyproject.toml file to include features promised in the template README noted in https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/41/files

Tasks
* Add dependencies to the pyproject.toml file. 
* Update Makefile
* Test out the installation and run the docs build to ensure everything works

**Comment by kefeimo** [comment]
fixed by #42 
manually closed.
