### ISSUE TITLE
Update message after running 'poetry install'

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#37]
When running 'poetry install', the following message appears on the CLI:

```
 > Running task 1 of 1: python scripts/post_generation.py
Project sucessfully generated!
Run `make` to show the available actions.
```

The current project does not have a Makefile from which to run 'make'. 

Tasks:
* Remove this message
* Also, 'sucessfully' is spelled wrong. Fix the spelling.

**Comment by kefeimo** [comment]
fixed by #44. Manually closed.
