### ISSUE TITLE
Update pyproject.toml

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#5]
The [current pyproject.toml](https://github.com/VOLTTRON/copier-poetry-volttron-agent/blob/main/project/pyproject.toml.jinja) under the project folder is outdated. For example, it uses the deprecated dependency 'volttron-client'. That dependency should be removed. 

Furthermore, the toml file should look more like the [pyproject.toml of volttron-core](https://github.com/VOLTTRON/volttron-core/blob/v10.0.1-alpha.3/pyproject.toml). Use that toml file as a guide to update pyproject.toml

References:

https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
https://snarky.ca/what-the-heck-is-pyproject-toml/

**Comment by kefeimo** [comment]
close by PR #20
