### ISSUE TITLE
Make sure main readme only references tools we use

### ISSUE THREAD

**Issue by craigpnnl** [VOLTTRON/copier-poetry-volttron-agent#51]
I write this for the black being referenced in the develop branch, but others should be checked and updated as well.

**Comment by kefeimo** [comment]
@craig8, 
Is there any action to take for updating the main README? e.g., for the following session:
(I looped @bonicim in the discussion as he is the main writer of the latest README.)

# Features

- [Poetry](https://github.com/sdispater/poetry) setup, with pre-defined `pyproject.toml`
- Documentation built with [Sphinx](https://www.sphinx-doc.org/en/master/)
- Pre-configured tools for code formatting, quality analysis and testing:
    - [yapf](https://github.com/google/yapf)
    - [isort](https://github.com/timothycrosley/isort),
    - [mypy](https://github.com/python/mypy),
    - [safety](https://github.com/pyupio/safety)
- Tests run with [pytest](https://github.com/pytest-dev/pytest) and plugins,
  with [coverage](https://github.com/nedbat/coveragepy) support
- Support for GitHub workflow and Gitlab CI
- Python 3.8 or above
- Auto-generated `CHANGELOG.md` from git commits (using Angular message style)
- All licenses from [choosealicense.com](https://choosealicense.com/appendix/)

Note: most of tools are defined in `pyproject.toml`, except `safety` is in `ci.yml`

**Comment by craigpnnl** [comment]
What does safety do?

**Comment by bonicim** [comment]
> What does safety do?

Safety checks your installed dependencies for known security vulnerabilities. It's a dependency that originally came with the template that we started with. Safety is used in ci.yml. The workflows need an update since there are some references to dependencies that we don't use such as duty). There's an issue to address these #46
