### ISSUE TITLE
Add mypy.ini configuration

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#6]
A mypy.ini configuration should be added under the project directory. Use the example from [volttron-core](https://github.com/VOLTTRON/volttron-core/blob/v10.0.1-alpha.3/mypy.ini). 

References:

https://en.wikipedia.org/wiki/INI_file
https://mypy.readthedocs.io/en/stable/config_file.html

**Comment by kefeimo** [comment]
Fixed by PR #27. Closed manually.
