### ISSUE TITLE
Add more Github Workflows to support CI/CD 

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#7]
Currently, the Github Workflows under 'project' has only [one workflow.](https://github.com/VOLTTRON/copier-poetry-volttron-agent/tree/main/project/.github/workflows) Copier should provide more workflows to support a more robust CI/CD pipeline to include automagically publishing to PyPi. Use the [workflows from volttron-core](https://github.com/VOLTTRON/volttron-core/tree/v10.0.1-alpha.3/.github/workflows) as a guide to create more workflows. Also, update the README to provide clear instructions on how to use and/or configure these workflows.

**Comment by kefeimo** [comment]
close by pr #28
